image: node:latest

stages:
  - lint
  - build

include:
  - project: 'docker/md-linter'
    ref: master
    file: '/helpers/.gitlab-ci-template.yml'

markdownlint:
  extends: .markdownlint

pages:
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn docs:build
  artifacts:
    paths:
    - public
  only:
  - master